# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PoleIO-UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow): 
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pieChartWidget = QtWidgets.QWidget(self.centralwidget)
        self.pieChartWidget.setGeometry(QtCore.QRect(540, 10, 241, 191))
        self.pieChartWidget.setObjectName("pieChartWidget")
        self.logTextView = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.logTextView.setGeometry(QtCore.QRect(30, 340, 721, 191))
        self.logTextView.setObjectName("logTextView")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(40, 50, 291, 31))
        self.textEdit.setObjectName("textEdit")
        self.btnBrowse = QtWidgets.QPushButton(self.centralwidget)
        self.btnBrowse.setGeometry(QtCore.QRect(340, 50, 71, 32))
        self.btnBrowse.setObjectName("btnBrowse")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 20, 161, 21))
        self.label.setObjectName("label")
        self.textNodeName = QtWidgets.QTextEdit(self.centralwidget)
        self.textNodeName.setGeometry(QtCore.QRect(40, 140, 291, 31))
        self.textNodeName.setObjectName("textNodeName")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 110, 161, 21))
        self.label_2.setObjectName("label_2")
        self.buttonVerify = QtWidgets.QPushButton(self.centralwidget)
        self.buttonVerify.setGeometry(QtCore.QRect(40, 200, 131, 41))
        self.buttonVerify.setObjectName("buttonVerify")
        self.lcdPoleCount = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdPoleCount.setGeometry(QtCore.QRect(630, 210, 121, 61))
        self.lcdPoleCount.setObjectName("lcdPoleCount")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(630, 280, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Pole.IO"))
        self.btnBrowse.setText(_translate("MainWindow", "Browse"))
        self.label.setText(_translate("MainWindow", "Image Sequence Directory"))
        self.label_2.setText(_translate("MainWindow", "Node Name"))
        self.buttonVerify.setText(_translate("MainWindow", "Verify Images"))
        self.label_3.setText(_translate("MainWindow", "POLE COUNT"))
